services:
  app:
    build: .

    container_name: online-store-app

    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: test
      DB_USERNAME: root
      DB_PASSWORD: REDACTED
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    container_name: online-store-mysql

    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_DATABASE: test

    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pREDACTED" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine

    container_name: online-store-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: