spring:
  application:
    name: 2027SpringProject

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Eating42@@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  logging:
    level:
      org:
        springframework:
          security=DEBUG:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

mybatis:
  mapper-locations: classpath:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html