spring:
  application:
    name: 2027SpringProject

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Eating42@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  logging:
    level:
      org:
        springframework:
          security=DEBUG:

mybatis:
  mapper-locations: classpath:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
